export { default as dataFormProductos } from './dataForms/dataFormProductos'
export { default as dataFormClientes } from './dataForms/dataFormClientes'
export { default as dataFormProveedores } from './dataForms/dataFormProveedores'
export { default as dataFormUsuarios } from './dataForms/dataFormUsuarios'
export { default as dataFormVentas } from './dataForms/dataFormVentas'
export { default as dataFormCompras } from './dataForms/dataFormCompras'
export { default as dataFormCategorias } from './dataForms/dataFormCategorias'

export { default as dataConsultasProductos } from './dataConsultas/dataConsultasProductos'
export { default as dataConsultasCategorias } from './dataConsultas/dataConsultasCategorias'
export { default as dataConsultasClientes } from './dataConsultas/dataConsultasClientes'
export { default as dataConsultasProveedores } from './dataConsultas/dataConsultasProveedores'
export { default as dataConsultasUsuarios } from './dataConsultas/dataConsultasUsuarios'
export { default as dataConsultasVentas } from './dataConsultas/dataConsultasVentas'
