const dataFormProveedores = {
	title: 'Proveedores',
	inputs: [
		{
			label: 'Identificación',
			placeholder: 'Escriba identificación',
			type: 'number',
			htmlFor: 'id',
			id: 'id',
			name: 'id',
			required: true,
			autoFocus: true,
		},
		{
			label: 'Nombre',
			placeholder: 'Escriba nombre del proveedor',
			type: 'text',
			htmlFor: 'nombre',
			id: 'nombre',
			name: 'nombre',
			required: true,
			autoFocus: false,
		},
		{
			label: 'Correo',
			placeholder: 'Escriba correo electrónico',
			type: 'text',
			htmlFor: 'email',
			id: 'email',
			name: 'email',
			required: true,
			autoFocus: false,
		},
		{
			label: 'Celular',
			placeholder: 'Escriba numero de celular',
			type: 'number',
			htmlFor: 'cel',
			id: 'cel',
			name: 'cel',
			required: true,
			autoFocus: false,
		},
		{
			label: 'Dirección',
			placeholder: 'Escriba dirección',
			type: 'text',
			htmlFor: 'dir',
			id: 'dir',
			name: 'dir',
			required: true,
			autoFocus: false,
		},
		{
			label: 'Ciudad',
			placeholder: 'Escriba ciudad',
			type: 'text',
			htmlFor: 'ciudad',
			id: 'ciudad',
			name: 'ciudad',
			required: true,
			autoFocus: false,
		},
	],
}

export default dataFormProveedores
